export const cartSelectors = {
  cartItemsContainer: '[class*="flex flex-col h-48"]',
  cartItemImage: 'img',
  cartItemTitle: '[style*="font-weight: bold"]',
  cartItemPrice: '[class*="currency"]',
  quantitySelect: '[formControlName="quantity"]',
  removeItemButton: '[label="Remover"]',
  clearCartButton: '[label="Limpar carrinho"]',
  emptyCartMessage: '[class*="pi-inbox"]',
  nextStepButton: '[label="Próximo"]',
  previousStepButton: '[label="Voltar"]',

  addressRadioButton: '[formControlName="address"]',
  addressLabel: 'label[for^="address"]',
  newAddressButton: '[class*="pi-plus"]',
  cancelAddressButton: 'button:contains("Cancelar")',

  typeResidenceSelect: '[formControlName="typeResidence"]',
  typePlaceSelect: '[formControlName="typePlace"]',
  streetInput: '#street',
  numberInput: '#number',
  neighborhoodInput: '#district',
  cepInput: '#cep',
  cityInput: '#city',
  stateSelect: '[formControlName="stateId"]',
  countryInput: '#country',
  observationsTextarea: '#notes',
  registerAddressButton: '[label="Cadastrar endereço"]',

  voucherCheckbox: '[formControlName="selectedExchangeVouchers"] p-checkbox',
  creditCardCheckbox: '[formControlName="selectedCardIds"] p-checkbox',
  installmentsSelect: '[formControlName="installments"]',
  newCreditCardButton: 'button:contains("Cadastrar novo cartão de crédito")',
  cancelCreditCardButton: 'button:contains("Cancelar")',

  cardNumberInput: '#cardNumber',
  printedNameInput: '#printedName',
  cpfInput: '#cpf',
  birthDateInput: '#birthDate',
  surnameInput: '#surname',
  cardFlagSelect: '[formControlName="cardFlag"]',
  securityCodeInput: '#securityCode',
  isMainCheckbox: '#isMainCard',
  registerCreditCardButton: '[label="Cadastrar cartão"]',

  voucherCodeInput: '[formControlName="code"]',
  applyVoucherButton: '[label="Aplicar"]',
  removeVoucherButton: '[class*="pi-times"]',
  voucherAppliedMessage: '[class*="pi-check-circle"]',
  voucherErrorMessage: '[class*="pi-exclamation-circle"]',

  subtotalValue: 'span:contains("Subtotal") + span',
  totalValue: 'span:contains("Total") + span',
  finalizePurchaseButton: '[label="Finalizar Compra"]',
  loginButton: '[href="/login"]',

  modal: 'app-modal',
  modalTitle: '[class*="modal-title"]',
  modalMessage: '[class*="modal-message"]',
  modalButton: '[class*="modal-button"]',

  requiresCreditCardAlert: '[class*="pi-exclamation-triangle"]',
  vouchersCoverTotalAlert: '[class*="pi-check-circle"]:contains("cobrem o valor total")',
}
